--local rainbow_delimiters = require 'rainbow-delimiters'
--
--vim.cmd("highlight RainbowDelimiterRed guifg=#eb6f92")
--vim.cmd("highlight RainbowDelimiterYellow guifg=#f6c177")
--
--vim.g.rainbow_delimiters = {
--  highlight = {
--    'RainbowDelimiterRed',
--    'RainbowDelimiterYellow',
--    'RainbowDelimiterBlue',
--    'RainbowDelimiterOrange',
--    'RainbowDelimiterGreen',
--    'RainbowDelimiterViolet',
--    'RainbowDelimiterCyan',
--  },
--}
